Some very basic doom profile troubleshooting
humacs/humacs pull request #30
Opened 2021-02-17 19:38 UTC by bernokl

2021-02-17 19:47 UTC, zachmandeville requested changes
Looks good!  There are just some tiny changes that will make it 100%!

2021-02-17 19:47 UTC, zachmandeville commented on docs/TROUBLESHOOT_DOOM.org
> +Not 100% on value of building again, but I do not think it hurts anything
building will "byte-compile and symlink installed packages".  It shouldn't be necessary when running doom sync, and I think this part could be removed.  The heading would then just be 'Run Doom Sync'

2021-02-17 19:47 UTC, zachmandeville commented on docs/TROUBLESHOOT_DOOM.org
> +emacs -nw --debut-init
change to `emacs -nw --debug-init`

2021-02-17 19:47 UTC, zachmandeville commented on docs/TROUBLESHOOT_DOOM.org
> +- HUMACSDIR :: Easy path to dir, not required but handy
keeping with the style of definitions above, perhaps add (e.g `~/ii/humacs`)

2021-03-04 19:28 UTC, bernokl commented on docs/TROUBLESHOOT_DOOM.org
> +Not 100% on value of building again, but I do not think it hurts anything
removed entire doom build secion, changed heading to "Run Doom sync"

2021-03-04 19:29 UTC, bernokl commented on docs/TROUBLESHOOT_DOOM.org
> +emacs -nw --debut-init
fixed typo, ty

2021-03-04 19:29 UTC, bernokl commented on docs/TROUBLESHOOT_DOOM.org
> +- HUMACSDIR :: Easy path to dir, not required but handy
added "eg..."

2021-03-12 02:10 UTC, merged